# Generated by Django 4.0.1 on 2022-04-26 00:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookMng', '0002_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='shopping_cart',
            field=models.BooleanField(default=False),
        )
    ]
